version: "3.8"
services:
  db:
    image: postgres:15
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5555:5555"
    volumes:
      - ./data:/var/lib/postgresql/data
